### ISSUE TITLE
Incompatibility with torch>=0.4.1

### ISSUE THREAD

**Issue by ilya-palachev** [eth-sri/diffai#1]
Hello,

I've tried to reproduce the workflow described in README, but faced with the following error:
```
TypeError: log_softmax() got multiple values for argument 'dim'
```
It happens due to conflict with newest `torch` version. Downgrading to `torch==0.4.0` resolves this issue.

**Comment by mmirman** [comment]
Fixed

**Comment by ilya-palachev** [comment]
Thanks, @mmirman !
