### ISSUE TITLE
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.

### ISSUE THREAD

**Issue by chenxi-yang** [eth-sri/diffai#12]
Run `python . -d "Point()" -d "Box()" -t "PGD()" -t "ZSwitch()" -n FFNN` with the newest version of PyTorch. Encountered the error in title. 
Location: 
File "./ai.py", line 130, in creluSwitch
    newerr  = h.ifThenElseL(should_box, 1 - should_boxer, gtz).to_dtype() * dom.errors
  File "[dir]/python3.8/site-packages/torch/tensor.py", line 511, in __rsub__
    return _C._VariableFunctions.rsub(self, other)

**Comment by mmirman** [comment]
From the README:  "python 3.6.7, and virtualenv, torch 0.4.1."  

This repository represents a scientific artefact meant to reproduce experiments from the associated papers, and as such is only supported with the versions of python and pytorch those experiments were reproduced with.  New versions of pytorch and python introduced breaking changes to their libraries, which could effect the outcome of these experiments.  

Future releases of DiffAI will update to newer versions of python and pytorch, but in the meantime I suggest making the changes manually in a cloned repo.
