### ISSUE TITLE
Meet Operation

### ISSUE THREAD

**Issue by chenxi-yang** [eth-sri/diffai#13]
Is the meet operation of hybrid zonotope supported by the current version?

**Comment by chenxi-yang** [comment]
The 2018 paper mentioned you have a meet-with-linear-constraint operation, which function is mapped to that operation? Thanks!

**Comment by mmirman** [comment]
The 2018 DiffAI paper mentioned that abstract domains typically support meet.  DiffAI does not support general meet.  ELINA supports general meet.

**Comment by tgehr** [comment]
> The 2018 DiffAI paper mentioned that abstract domains typically support meet.  DiffAI does not support general meet.  ELINA supports general meet.

Also see: https://github.com/eth-sri/ELINA/blob/master/elina_zonotope/elina_box_meetjoin.c#L757

**Comment by chenxi-yang** [comment]
Thank you!
